In [6]:
import pandas as pd

In [7]:
import numpy as np

In [8]:
lotto = pd.read_csv('/Users/pickoffwhite/Code/kindergarten-lotto/20171103_ KQED_KinderAssignmentData_201718 - K Placement 2017-2018.csv', dtype = object)

In [9]:
codes = pd.read_csv("/Users/pickoffwhite/Code/kindergarten-lotto/SchoolCodes.csv")

In [10]:
lotto['got1stchoice'] = np.where(lotto['1'] == lotto['School Enrolled In As Of 11/03/2017'], 'yes', 'no')

In [11]:
lotto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4611 entries, 0 to 4610
Data columns (total 99 columns):
StudentNo                                 4611 non-null object
1                                         4611 non-null object
2                                         3856 non-null object
3                                         3441 non-null object
4                                         3028 non-null object
5                                         2657 non-null object
6                                         2361 non-null object
7                                         2114 non-null object
8                                         1938 non-null object
9                                         1804 non-null object
10                                        1668 non-null object
11                                        1147 non-null object
12                                        1027 non-null object
13                                        992 non-null object
14                                        949 non-null object
15                                        912 non-null object
16                                        881 non-null object
17                                        844 non-null object
18                                        796 non-null object
19                                        769 non-null object
20                                        738 non-null object
21                                        685 non-null object
22                                        649 non-null object
23                                        627 non-null object
24                                        605 non-null object
25                                        577 non-null object
26                                        544 non-null object
27                                        521 non-null object
28                                        503 non-null object
29                                        477 non-null object
30                                        444 non-null object
31                                        397 non-null object
32                                        374 non-null object
33                                        353 non-null object
34                                        338 non-null object
35                                        322 non-null object
36                                        300 non-null object
37                                        283 non-null object
38                                        271 non-null object
39                                        260 non-null object
40                                        245 non-null object
41                                        226 non-null object
42                                        212 non-null object
43                                        201 non-null object
44                                        188 non-null object
45                                        174 non-null object
46                                        166 non-null object
47                                        161 non-null object
48                                        154 non-null object
49                                        143 non-null object
50                                        137 non-null object
51                                        118 non-null object
52                                        115 non-null object
53                                        109 non-null object
54                                        106 non-null object
55                                        106 non-null object
56                                        99 non-null object
57                                        95 non-null object
58                                        91 non-null object
59                                        91 non-null object
60                                        88 non-null object
61                                        84 non-null object
62                                        83 non-null object
63                                        79 non-null object
64                                        77 non-null object
65                                        73 non-null object
66                                        69 non-null object
67                                        62 non-null object
68                                        59 non-null object
69                                        56 non-null object
70                                        53 non-null object
71                                        49 non-null object
72                                        44 non-null object
73                                        41 non-null object
74                                        40 non-null object
75                                        39 non-null object
76                                        38 non-null object
77                                        37 non-null object
78                                        35 non-null object
79                                        33 non-null object
80                                        29 non-null object
81                                        23 non-null object
82                                        21 non-null object
83                                        13 non-null object
84                                        9 non-null object
85                                        7 non-null object
86                                        2 non-null object
87                                        2 non-null object
88                                        2 non-null object
89                                        2 non-null object
90                                        2 non-null object
91                                        1 non-null object
92                                        1 non-null object
Round 1 Assignment                        4470 non-null object
School Enrolled In As Of 11/03/2017       4043 non-null object
Student's Ethnicity                       4389 non-null object
Does Student Live In CTIP1 Zone? (y/n)    4611 non-null object
Student's Residential Zip Code            4611 non-null object
got1stchoice                              4611 non-null object
dtypes: object(99)
memory usage: 3.5+ MB

In [12]:
lotto.head()

,StudentNo,1,2,3,4,5,6,7,8,9,...,89,90,91,92,Round 1 Assignment,School Enrolled In As Of 11/03/2017,Student's Ethnicity,Does Student Live In CTIP1 Zone? (y/n),Student's Residential Zip Code,got1stchoice
0,1,848,569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,848,848,"White, Not of Hispanic Origin",N,94118,yes
1,2,420,420,537,729,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,729,729,Hispanic,N,94112,no
2,3,478,589,722,664,539,796,420,413,569,...,NaN,NaN,NaN,NaN,722,722,"White, Not of Hispanic Origin",N,94131,no
3,4,782,676,478,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,782,782,Asian or Pacific Islander,N,94127,yes
4,5,420,618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,420,420,Hispanic,Y,94110,yes

In [13]:
lotto.got1stchoice.value_counts()

yes    2810
no     1801
Name: got1stchoice, dtype: int64

In [14]:
lotto.got1stchoice.value_counts('yes')

yes    0.609412
no     0.390588
Name: got1stchoice, dtype: float64

In [15]:
lotto7 = lotto[['School Enrolled In As Of 11/03/2017','1','2','3','4','5']]

In [16]:
lotto7["exists"] = lotto7.drop("School Enrolled In As Of 11/03/2017", 1).isin(lotto7["School Enrolled In As Of 11/03/2017"]).any(1)
print(lotto7)

     School Enrolled In As Of 11/03/2017    1    2    3    4    5  exists
0                                    848  848  569  NaN  NaN  NaN    True
1                                    729  420  420  537  729  NaN    True
2                                    722  478  589  722  664  539    True
3                                    782  782  676  478  NaN  NaN    True
4                                    420  420  618  NaN  NaN  NaN    True
5                                    838  838  746  478  876  488    True
6                                    614  485  876  513  513  478   False
7                                    859  859  449  790  NaN  NaN    True
8                                    420  420  NaN  NaN  NaN  NaN    True
9                                    782  782  NaN  NaN  NaN  NaN    True
10                                   862  485  676  862  750  746    True
11                                   676  676  796  485  478  478    True
12                                   842  842  722  575  478  488    True
13                                   490  862  876  509  862  876   False
14                                   NaN  676  485  750  644  782   False
15                                   746  746  NaN  NaN  NaN  NaN    True
16                                   782  676  782  750  485  644    True
17                                   435  435  NaN  NaN  NaN  NaN    True
18                                   NaN  796  420  478  722  876   False
19                                   676  676  782  644  750  862    True
20                                   478  478  735  420  435  485    True
21                                   867  867  NaN  NaN  NaN  NaN    True
22                                   488  488  NaN  NaN  NaN  NaN    True
23                                   860  569  479  782  750  644   False
24                                   525  862  867  NaN  NaN  NaN   False
25                                   562  562  NaN  NaN  NaN  NaN    True
26                                   782  782  676  485  509  544    True
27                                   875  664  796  479  625  NaN   False
28                                   562  562  NaN  NaN  NaN  NaN    True
29                                   718  718  589  796  735  786    True
...                                  ...  ...  ...  ...  ...  ...     ...
4581                                 656  420  420  876  722  796   False
4582                                 485  485  NaN  NaN  NaN  NaN    True
4583                                 859  449  NaN  NaN  NaN  NaN   False
4584                                 814  814  NaN  NaN  NaN  NaN    True
4585                                 938  589  718  478  796  722   False
4586                                 507  507  NaN  NaN  NaN  NaN    True
4587                                 644  644  676  782  750  589    True
4588                                 456  537  420  456  680  618    True
4589                                 796  796  NaN  NaN  NaN  NaN    True
4590                                 614  603  656  722  575  NaN   False
4591                                 544  435  413  664  569  676   False
4592                                 525  823  525  801  790  718    True
4593                                 796  796  478  589  722  876    True
4594                                 521  521  NaN  NaN  NaN  NaN    True
4595                                 760  760  449  796  420  435    True
4596                                 750  750  876  876  478  478    True
4597                                 420  796  420  420  876  478    True
4598                                 816  816  NaN  NaN  NaN  NaN    True
4599                                 670  670  750  644  876  796    True
4600                                 490  872  490  638  834  801    True
4601                                 449  449  796  537  814  735    True
4602                                 478  478  478  420  796  644    True
4603                                 618  618  714  537  729  723    True
4604                                 201  478  478  876  876  796   False
4605                                 670  644  413  664  435  670    True
4606                                 867  867  NaN  NaN  NaN  NaN    True
4607                                 618  618  796  760  NaN  NaN    True
4608                                 820  820  488  691  691  NaN    True
4609                                 834  834  490  638  562  525    True
4610                                 718  718  722  814  823  413    True

[4611 rows x 7 columns]

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [17]:
lotto7.exists.value_counts(True)

True     0.766645
False    0.233355
Name: exists, dtype: float64

In [18]:
lotto10 = lotto[['School Enrolled In As Of 11/03/2017','1','2','3','4','5', '6', '7', '8', '9', '10']]

In [19]:
lotto10['exists'] = lotto10.drop("School Enrolled In As Of 11/03/2017", 1).isin(lotto10["School Enrolled In As Of 11/03/2017"]).any(1)
print(lotto10)

     School Enrolled In As Of 11/03/2017    1    2    3    4    5    6    7  \
0                                    848  848  569  NaN  NaN  NaN  NaN  NaN
1                                    729  420  420  537  729  NaN  NaN  NaN
2                                    722  478  589  722  664  539  796  420
3                                    782  782  676  478  NaN  NaN  NaN  NaN
4                                    420  420  618  NaN  NaN  NaN  NaN  NaN
5                                    838  838  746  478  876  488  848  729
6                                    614  485  876  513  513  478  862  862
7                                    859  859  449  790  NaN  NaN  NaN  NaN
8                                    420  420  NaN  NaN  NaN  NaN  NaN  NaN
9                                    782  782  NaN  NaN  NaN  NaN  NaN  NaN
10                                   862  485  676  862  750  746  539  435
11                                   676  676  796  485  478  478  420  420
12                                   842  842  722  575  478  488  876  420
13                                   490  862  876  509  862  876  488  490
14                                   NaN  676  485  750  644  782  876  746
15                                   746  746  NaN  NaN  NaN  NaN  NaN  NaN
16                                   782  676  782  750  485  644  876  862
17                                   435  435  NaN  NaN  NaN  NaN  NaN  NaN
18                                   NaN  796  420  478  722  876  718  589
19                                   676  676  782  644  750  862  876  539
20                                   478  478  735  420  435  485  676  750
21                                   867  867  NaN  NaN  NaN  NaN  NaN  NaN
22                                   488  488  NaN  NaN  NaN  NaN  NaN  NaN
23                                   860  569  479  782  750  644  413  876
24                                   525  862  867  NaN  NaN  NaN  NaN  NaN
25                                   562  562  NaN  NaN  NaN  NaN  NaN  NaN
26                                   782  782  676  485  509  544  750  644
27                                   875  664  796  479  625  NaN  NaN  NaN
28                                   562  562  NaN  NaN  NaN  NaN  NaN  NaN
29                                   718  718  589  796  735  786  420  505
...                                  ...  ...  ...  ...  ...  ...  ...  ...
4581                                 656  420  420  876  722  796  862  488
4582                                 485  485  NaN  NaN  NaN  NaN  NaN  NaN
4583                                 859  449  NaN  NaN  NaN  NaN  NaN  NaN
4584                                 814  814  NaN  NaN  NaN  NaN  NaN  NaN
4585                                 938  589  718  478  796  722  814  735
4586                                 507  507  NaN  NaN  NaN  NaN  NaN  NaN
4587                                 644  644  676  782  750  589  664  862
4588                                 456  537  420  456  680  618  760  723
4589                                 796  796  NaN  NaN  NaN  NaN  NaN  NaN
4590                                 614  603  656  722  575  NaN  NaN  NaN
4591                                 544  435  413  664  569  676  848  485
4592                                 525  823  525  801  790  718  638  NaN
4593                                 796  796  478  589  722  876  842  718
4594                                 521  521  NaN  NaN  NaN  NaN  NaN  NaN
4595                                 760  760  449  796  420  435  488  478
4596                                 750  750  876  876  478  478  485  676
4597                                 420  796  420  420  876  478  589  718
4598                                 816  816  NaN  NaN  NaN  NaN  NaN  NaN
4599                                 670  670  750  644  876  796  NaN  NaN
4600                                 490  872  490  638  834  801  562  562
4601                                 449  449  796  537  814  735  723  478
4602                                 478  478  478  420  796  644  842  722
4603                                 618  618  714  537  729  723  NaN  NaN
4604                                 201  478  478  876  876  796  589  420
4605                                 670  644  413  664  435  670  497  569
4606                                 867  867  NaN  NaN  NaN  NaN  NaN  NaN
4607                                 618  618  796  760  NaN  NaN  NaN  NaN
4608                                 820  820  488  691  691  NaN  NaN  NaN
4609                                 834  834  490  638  562  525  650  NaN
4610                                 718  718  722  814  823  413  420  NaN

        8    9   10  exists
0     NaN  NaN  NaN    True
1     NaN  NaN  NaN    True
2     413  569  750    True
3     NaN  NaN  NaN    True
4     NaN  NaN  NaN    True
5     569  796  676    True
6     782  760  NaN   False
7     NaN  NaN  NaN    True
8     NaN  NaN  NaN    True
9     NaN  NaN  NaN    True
10    782  644  876    True
11    497  589  876    True
12    796  539  862    True
13    NaN  NaN  NaN    True
14    876  NaN  NaN   False
15    NaN  NaN  NaN    True
16    876  544  435    True
17    NaN  NaN  NaN    True
18    479  413  485   False
19    NaN  NaN  NaN    True
20    544  876  505    True
21    NaN  NaN  NaN    True
22    NaN  NaN  NaN    True
23    435  485  676   False
24    NaN  NaN  NaN   False
25    NaN  NaN  NaN    True
26    569  549  735    True
27    NaN  NaN  NaN   False
28    NaN  NaN  NaN    True
29    478  569  823    True
...   ...  ...  ...     ...
4581  478  842  656    True
4582  NaN  NaN  NaN    True
4583  NaN  NaN  NaN   False
4584  NaN  NaN  NaN    True
4585  569  420  435   False
4586  NaN  NaN  NaN    True
4587  569  544  NaN    True
4588  NaN  NaN  NaN    True
4589  NaN  NaN  NaN    True
4590  NaN  NaN  NaN   False
4591  750  544  746    True
4592  NaN  NaN  NaN    True
4593  513  NaN  NaN    True
4594  NaN  NaN  NaN    True
4595  722  479  539    True
4596  644  NaN  NaN    True
4597  485  722  537    True
4598  NaN  NaN  NaN    True
4599  NaN  NaN  NaN    True
4600  823  790  859    True
4601  664  676  420    True
4602  676  479  735    True
4603  NaN  NaN  NaN    True
4604  420  575  718   False
4605  848  750  842    True
4606  NaN  NaN  NaN    True
4607  NaN  NaN  NaN    True
4608  NaN  NaN  NaN    True
4609  NaN  NaN  NaN    True
4610  NaN  NaN  NaN    True

[4611 rows x 12 columns]

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [20]:
lotto10.reset_index()

,index,School Enrolled In As Of 11/03/2017,1,2,3,4,5,6,7,8,9,10,exists
0,0,848,848,569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,1,729,420,420,537,729,NaN,NaN,NaN,NaN,NaN,NaN,True
2,2,722,478,589,722,664,539,796,420,413,569,750,True
3,3,782,782,676,478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4,4,420,420,618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
5,5,838,838,746,478,876,488,848,729,569,796,676,True
6,6,614,485,876,513,513,478,862,862,782,760,NaN,False
7,7,859,859,449,790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
8,8,420,420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9,9,782,782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
10,10,862,485,676,862,750,746,539,435,782,644,876,True
11,11,676,676,796,485,478,478,420,420,497,589,876,True
12,12,842,842,722,575,478,488,876,420,796,539,862,True
13,13,490,862,876,509,862,876,488,490,NaN,NaN,NaN,True
14,14,NaN,676,485,750,644,782,876,746,876,NaN,NaN,False
15,15,746,746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
16,16,782,676,782,750,485,644,876,862,876,544,435,True
17,17,435,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
18,18,NaN,796,420,478,722,876,718,589,479,413,485,False
19,19,676,676,782,644,750,862,876,539,NaN,NaN,NaN,True
20,20,478,478,735,420,435,485,676,750,544,876,505,True
21,21,867,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
22,22,488,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
23,23,860,569,479,782,750,644,413,876,435,485,676,False
24,24,525,862,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
25,25,562,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
26,26,782,782,676,485,509,544,750,644,569,549,735,True
27,27,875,664,796,479,625,NaN,NaN,NaN,NaN,NaN,NaN,False
28,28,562,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
29,29,718,718,589,796,735,786,420,505,478,569,823,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4581,4581,656,420,420,876,722,796,862,488,478,842,656,True
4582,4582,485,485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4583,4583,859,449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4584,4584,814,814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4585,4585,938,589,718,478,796,722,814,735,569,420,435,False
4586,4586,507,507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4587,4587,644,644,676,782,750,589,664,862,569,544,NaN,True
4588,4588,456,537,420,456,680,618,760,723,NaN,NaN,NaN,True
4589,4589,796,796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4590,4590,614,603,656,722,575,NaN,NaN,NaN,NaN,NaN,NaN,False
4591,4591,544,435,413,664,569,676,848,485,750,544,746,True
4592,4592,525,823,525,801,790,718,638,NaN,NaN,NaN,NaN,True
4593,4593,796,796,478,589,722,876,842,718,513,NaN,NaN,True
4594,4594,521,521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4595,4595,760,760,449,796,420,435,488,478,722,479,539,True
4596,4596,750,750,876,876,478,478,485,676,644,NaN,NaN,True
4597,4597,420,796,420,420,876,478,589,718,485,722,537,True
4598,4598,816,816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4599,4599,670,670,750,644,876,796,NaN,NaN,NaN,NaN,NaN,True
4600,4600,490,872,490,638,834,801,562,562,823,790,859,True
4601,4601,449,449,796,537,814,735,723,478,664,676,420,True
4602,4602,478,478,478,420,796,644,842,722,676,479,735,True
4603,4603,618,618,714,537,729,723,NaN,NaN,NaN,NaN,NaN,True
4604,4604,201,478,478,876,876,796,589,420,420,575,718,False
4605,4605,670,644,413,664,435,670,497,569,848,750,842,True
4606,4606,867,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4607,4607,618,618,796,760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4608,4608,820,820,488,691,691,NaN,NaN,NaN,NaN,NaN,NaN,True
4609,4609,834,834,490,638,562,525,650,NaN,NaN,NaN,NaN,True
4610,4610,718,718,722,814,823,413,420,NaN,NaN,NaN,NaN,True

In [21]:
lotto10.exists.value_counts(True)

True     0.796573
False    0.203427
Name: exists, dtype: float64

In [22]:
random = lotto.drop(['StudentNo', 'School Enrolled In As Of 11/03/2017'], axis=1)

In [23]:
random['notrandom'] = random.drop('Round 1 Assignment', 1).isin(random['Round 1 Assignment']).any(1)
print(random)

        1    2    3    4    5    6    7    8    9   10    ...      89   90  \
0     848  569  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
1     420  420  537  729  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
2     478  589  722  664  539  796  420  413  569  750    ...     NaN  NaN
3     782  676  478  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4     420  618  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
5     838  746  478  876  488  848  729  569  796  676    ...     NaN  NaN
6     485  876  513  513  478  862  862  782  760  NaN    ...     NaN  NaN
7     859  449  790  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
8     420  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
9     782  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
10    485  676  862  750  746  539  435  782  644  876    ...     NaN  NaN
11    676  796  485  478  478  420  420  497  589  876    ...     NaN  NaN
12    842  722  575  478  488  876  420  796  539  862    ...     NaN  NaN
13    862  876  509  862  876  488  490  NaN  NaN  NaN    ...     NaN  NaN
14    676  485  750  644  782  876  746  876  NaN  NaN    ...     NaN  NaN
15    746  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
16    676  782  750  485  644  876  862  876  544  435    ...     NaN  NaN
17    435  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
18    796  420  478  722  876  718  589  479  413  485    ...     NaN  NaN
19    676  782  644  750  862  876  539  NaN  NaN  NaN    ...     NaN  NaN
20    478  735  420  435  485  676  750  544  876  505    ...     NaN  NaN
21    867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
22    488  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
23    569  479  782  750  644  413  876  435  485  676    ...     NaN  NaN
24    862  867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
25    562  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
26    782  676  485  509  544  750  644  569  549  735    ...     NaN  NaN
27    664  796  479  625  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
28    562  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
29    718  589  796  735  786  420  505  478  569  823    ...     NaN  NaN
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...     ...  ...
4581  420  420  876  722  796  862  488  478  842  656    ...     NaN  NaN
4582  485  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4583  449  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4584  814  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4585  589  718  478  796  722  814  735  569  420  435    ...     NaN  NaN
4586  507  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4587  644  676  782  750  589  664  862  569  544  NaN    ...     NaN  NaN
4588  537  420  456  680  618  760  723  NaN  NaN  NaN    ...     NaN  NaN
4589  796  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4590  603  656  722  575  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4591  435  413  664  569  676  848  485  750  544  746    ...     NaN  NaN
4592  823  525  801  790  718  638  NaN  NaN  NaN  NaN    ...     NaN  NaN
4593  796  478  589  722  876  842  718  513  NaN  NaN    ...     NaN  NaN
4594  521  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4595  760  449  796  420  435  488  478  722  479  539    ...     NaN  NaN
4596  750  876  876  478  478  485  676  644  NaN  NaN    ...     NaN  NaN
4597  796  420  420  876  478  589  718  485  722  537    ...     NaN  NaN
4598  816  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4599  670  750  644  876  796  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4600  872  490  638  834  801  562  562  823  790  859    ...     NaN  NaN
4601  449  796  537  814  735  723  478  664  676  420    ...     NaN  NaN
4602  478  478  420  796  644  842  722  676  479  735    ...     NaN  NaN
4603  618  714  537  729  723  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4604  478  478  876  876  796  589  420  420  575  718    ...     NaN  NaN
4605  644  413  664  435  670  497  569  848  750  842    ...     NaN  NaN
4606  867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4607  618  796  760  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4608  820  488  691  691  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4609  834  490  638  562  525  650  NaN  NaN  NaN  NaN    ...     NaN  NaN
4610  718  722  814  823  413  420  NaN  NaN  NaN  NaN    ...     NaN  NaN

       91   92 Round 1 Assignment            Student's Ethnicity  \
0     NaN  NaN                848  White, Not of Hispanic Origin
1     NaN  NaN                729                       Hispanic
2     NaN  NaN                722  White, Not of Hispanic Origin
3     NaN  NaN                782      Asian or Pacific Islander
4     NaN  NaN                420                       Hispanic
5     NaN  NaN                838      Asian or Pacific Islander
6     NaN  NaN                760              Declines To State
7     NaN  NaN                859                       Hispanic
8     NaN  NaN                420              Declines To State
9     NaN  NaN                782              Declines To State
10    NaN  NaN                862      Asian or Pacific Islander
11    NaN  NaN                676              Declines To State
12    NaN  NaN                842  White, Not of Hispanic Origin
13    NaN  NaN                490      Asian or Pacific Islander
14    NaN  NaN                NaN      Asian or Pacific Islander
15    NaN  NaN                746              Declines To State
16    NaN  NaN                782      Asian or Pacific Islander
17    NaN  NaN                435              Declines To State
18    NaN  NaN                420              Declines To State
19    NaN  NaN                676      Asian or Pacific Islander
20    NaN  NaN                478  White, Not of Hispanic Origin
21    NaN  NaN                867      Asian or Pacific Islander
22    NaN  NaN                488              Declines To State
23    NaN  NaN                656              Declines To State
24    NaN  NaN                867              Declines To State
25    NaN  NaN                562                       Hispanic
26    NaN  NaN                782      Asian or Pacific Islander
27    NaN  NaN                625                       Hispanic
28    NaN  NaN                562                       Hispanic
29    NaN  NaN                718  White, Not of Hispanic Origin
...   ...  ...                ...                            ...
4581  NaN  NaN                656  White, Not of Hispanic Origin
4582  NaN  NaN                485      Asian or Pacific Islander
4583  NaN  NaN                449                            NaN
4584  NaN  NaN                814                       Hispanic
4585  NaN  NaN                589  White, Not of Hispanic Origin
4586  NaN  NaN                507                            NaN
4587  NaN  NaN                644      Asian or Pacific Islander
4588  NaN  NaN                456                       Hispanic
4589  NaN  NaN                796                       Hispanic
4590  NaN  NaN                603                       Hispanic
4591  NaN  NaN                859      Asian or Pacific Islander
4592  NaN  NaN                525  Black, Not of Hispanic Origin
4593  NaN  NaN                796      Asian or Pacific Islander
4594  NaN  NaN                521                       Hispanic
4595  NaN  NaN                760      Asian or Pacific Islander
4596  NaN  NaN                750      Asian or Pacific Islander
4597  NaN  NaN                420                            NaN
4598  NaN  NaN                816                       Hispanic
4599  NaN  NaN                670  White, Not of Hispanic Origin
4600  NaN  NaN                490      Asian or Pacific Islander
4601  NaN  NaN                449                            NaN
4602  NaN  NaN                478  White, Not of Hispanic Origin
4603  NaN  NaN                618                       Hispanic
4604  NaN  NaN                816                            NaN
4605  NaN  NaN                670  White, Not of Hispanic Origin
4606  NaN  NaN                867      Asian or Pacific Islander
4607  NaN  NaN                618                            NaN
4608  NaN  NaN                820                       Hispanic
4609  NaN  NaN                834                            NaN
4610  NaN  NaN                718  White, Not of Hispanic Origin

     Does Student Live In CTIP1 Zone? (y/n) Student's Residential Zip Code  \
0                                         N                          94118
1                                         N                          94112
2                                         N                          94131
3                                         N                          94127
4                                         Y                          94110
5                                         N                          94134
6                                         N                          94134
7                                         N                          94102
8                                         Y                          94107
9                                         N                          94112
10                                        N                          94116
11                                        Y                          94107
12                                        N                          94127
13                                        N                          94112
14                                        N                          94132
15                                        N                          94112
16                                        N                          94132
17                                        N                          94121
18                                        N                          94114
19                                        N                          94112
20                                        N                          94122
21                                        N                          94134
22                                        N                          94112
23                                        N                          94131
24                                        N                          94116
25                                        N                          94117
26                                        N                          94103
27                                        N                          94129
28                                        N                          94107
29                                        N                          94114
...                                     ...                            ...
4581                                      N                          94112
4582                                      N                          94112
4583                                      Y                          94115
4584                                      N                          94124
4585                                      N                          94117
4586                                      Y                          94124
4587                                      N                          94122
4588                                      N                          94124
4589                                      N                          94134
4590                                      N                          94112
4591                                      N                          94121
4592                                      N                          94115
4593                                      N                          94134
4594                                      N                          94134
4595                                      N                          94124
4596                                      N                          94122
4597                                      N                          94114
4598                                      Y                          94110
4599                                      N                          94127
4600                                      N                          94108
4601                                      Y                          94124
4602                                      Y                          94109
4603                                      Y                          94110
4604                                      N                          94131
4605                                      N                          94118
4606                                      N                          94134
4607                                      N                          94110
4608                                      N                          94112
4609                                      Y                          94109
4610                                      Y                          94115

     got1stchoice notrandom
0             yes      True
1              no      True
2              no      True
3             yes      True
4             yes      True
5             yes      True
6              no      True
7             yes      True
8             yes      True
9             yes      True
10             no      True
11            yes      True
12            yes      True
13             no      True
14             no     False
15            yes      True
16             no      True
17            yes      True
18             no      True
19            yes      True
20            yes      True
21            yes      True
22            yes      True
23             no      True
24             no      True
25            yes      True
26            yes      True
27             no      True
28            yes      True
29            yes      True
...           ...       ...
4581           no      True
4582          yes      True
4583           no      True
4584          yes      True
4585           no      True
4586          yes      True
4587          yes      True
4588           no      True
4589          yes      True
4590           no      True
4591           no      True
4592           no      True
4593          yes      True
4594          yes      True
4595          yes      True
4596          yes      True
4597           no      True
4598          yes      True
4599          yes      True
4600           no      True
4601          yes      True
4602          yes      True
4603          yes      True
4604           no      True
4605           no      True
4606          yes      True
4607          yes      True
4608          yes      True
4609          yes      True
4610          yes      True

[4611 rows x 98 columns]

In [24]:
random.reset_index()

,index,1,2,3,4,5,6,7,8,9,...,89,90,91,92,Round 1 Assignment,Student's Ethnicity,Does Student Live In CTIP1 Zone? (y/n),Student's Residential Zip Code,got1stchoice,notrandom
0,0,848,569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,848,"White, Not of Hispanic Origin",N,94118,yes,True
1,1,420,420,537,729,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,729,Hispanic,N,94112,no,True
2,2,478,589,722,664,539,796,420,413,569,...,NaN,NaN,NaN,NaN,722,"White, Not of Hispanic Origin",N,94131,no,True
3,3,782,676,478,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,782,Asian or Pacific Islander,N,94127,yes,True
4,4,420,618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,420,Hispanic,Y,94110,yes,True
5,5,838,746,478,876,488,848,729,569,796,...,NaN,NaN,NaN,NaN,838,Asian or Pacific Islander,N,94134,yes,True
6,6,485,876,513,513,478,862,862,782,760,...,NaN,NaN,NaN,NaN,760,Declines To State,N,94134,no,True
7,7,859,449,790,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,859,Hispanic,N,94102,yes,True
8,8,420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,420,Declines To State,Y,94107,yes,True
9,9,782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,782,Declines To State,N,94112,yes,True
10,10,485,676,862,750,746,539,435,782,644,...,NaN,NaN,NaN,NaN,862,Asian or Pacific Islander,N,94116,no,True
11,11,676,796,485,478,478,420,420,497,589,...,NaN,NaN,NaN,NaN,676,Declines To State,Y,94107,yes,True
12,12,842,722,575,478,488,876,420,796,539,...,NaN,NaN,NaN,NaN,842,"White, Not of Hispanic Origin",N,94127,yes,True
13,13,862,876,509,862,876,488,490,NaN,NaN,...,NaN,NaN,NaN,NaN,490,Asian or Pacific Islander,N,94112,no,True
14,14,676,485,750,644,782,876,746,876,NaN,...,NaN,NaN,NaN,NaN,NaN,Asian or Pacific Islander,N,94132,no,False
15,15,746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,746,Declines To State,N,94112,yes,True
16,16,676,782,750,485,644,876,862,876,544,...,NaN,NaN,NaN,NaN,782,Asian or Pacific Islander,N,94132,no,True
17,17,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,435,Declines To State,N,94121,yes,True
18,18,796,420,478,722,876,718,589,479,413,...,NaN,NaN,NaN,NaN,420,Declines To State,N,94114,no,True
19,19,676,782,644,750,862,876,539,NaN,NaN,...,NaN,NaN,NaN,NaN,676,Asian or Pacific Islander,N,94112,yes,True
20,20,478,735,420,435,485,676,750,544,876,...,NaN,NaN,NaN,NaN,478,"White, Not of Hispanic Origin",N,94122,yes,True
21,21,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,867,Asian or Pacific Islander,N,94134,yes,True
22,22,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,488,Declines To State,N,94112,yes,True
23,23,569,479,782,750,644,413,876,435,485,...,NaN,NaN,NaN,NaN,656,Declines To State,N,94131,no,True
24,24,862,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,867,Declines To State,N,94116,no,True
25,25,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,562,Hispanic,N,94117,yes,True
26,26,782,676,485,509,544,750,644,569,549,...,NaN,NaN,NaN,NaN,782,Asian or Pacific Islander,N,94103,yes,True
27,27,664,796,479,625,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,625,Hispanic,N,94129,no,True
28,28,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,562,Hispanic,N,94107,yes,True
29,29,718,589,796,735,786,420,505,478,569,...,NaN,NaN,NaN,NaN,718,"White, Not of Hispanic Origin",N,94114,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4581,4581,420,420,876,722,796,862,488,478,842,...,NaN,NaN,NaN,NaN,656,"White, Not of Hispanic Origin",N,94112,no,True
4582,4582,485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,485,Asian or Pacific Islander,N,94112,yes,True
4583,4583,449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,449,NaN,Y,94115,no,True
4584,4584,814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,814,Hispanic,N,94124,yes,True
4585,4585,589,718,478,796,722,814,735,569,420,...,NaN,NaN,NaN,NaN,589,"White, Not of Hispanic Origin",N,94117,no,True
4586,4586,507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,507,NaN,Y,94124,yes,True
4587,4587,644,676,782,750,589,664,862,569,544,...,NaN,NaN,NaN,NaN,644,Asian or Pacific Islander,N,94122,yes,True
4588,4588,537,420,456,680,618,760,723,NaN,NaN,...,NaN,NaN,NaN,NaN,456,Hispanic,N,94124,no,True
4589,4589,796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,796,Hispanic,N,94134,yes,True
4590,4590,603,656,722,575,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,603,Hispanic,N,94112,no,True
4591,4591,435,413,664,569,676,848,485,750,544,...,NaN,NaN,NaN,NaN,859,Asian or Pacific Islander,N,94121,no,True
4592,4592,823,525,801,790,718,638,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,525,"Black, Not of Hispanic Origin",N,94115,no,True
4593,4593,796,478,589,722,876,842,718,513,NaN,...,NaN,NaN,NaN,NaN,796,Asian or Pacific Islander,N,94134,yes,True
4594,4594,521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,521,Hispanic,N,94134,yes,True
4595,4595,760,449,796,420,435,488,478,722,479,...,NaN,NaN,NaN,NaN,760,Asian or Pacific Islander,N,94124,yes,True
4596,4596,750,876,876,478,478,485,676,644,NaN,...,NaN,NaN,NaN,NaN,750,Asian or Pacific Islander,N,94122,yes,True
4597,4597,796,420,420,876,478,589,718,485,722,...,NaN,NaN,NaN,NaN,420,NaN,N,94114,no,True
4598,4598,816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,816,Hispanic,Y,94110,yes,True
4599,4599,670,750,644,876,796,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,670,"White, Not of Hispanic Origin",N,94127,yes,True
4600,4600,872,490,638,834,801,562,562,823,790,...,NaN,NaN,NaN,NaN,490,Asian or Pacific Islander,N,94108,no,True
4601,4601,449,796,537,814,735,723,478,664,676,...,NaN,NaN,NaN,NaN,449,NaN,Y,94124,yes,True
4602,4602,478,478,420,796,644,842,722,676,479,...,NaN,NaN,NaN,NaN,478,"White, Not of Hispanic Origin",Y,94109,yes,True
4603,4603,618,714,537,729,723,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,618,Hispanic,Y,94110,yes,True
4604,4604,478,478,876,876,796,589,420,420,575,...,NaN,NaN,NaN,NaN,816,NaN,N,94131,no,True
4605,4605,644,413,664,435,670,497,569,848,750,...,NaN,NaN,NaN,NaN,670,"White, Not of Hispanic Origin",N,94118,no,True
4606,4606,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,867,Asian or Pacific Islander,N,94134,yes,True
4607,4607,618,796,760,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,618,NaN,N,94110,yes,True
4608,4608,820,488,691,691,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,820,Hispanic,N,94112,yes,True
4609,4609,834,490,638,562,525,650,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,834,NaN,Y,94109,yes,True
4610,4610,718,722,814,823,413,420,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,718,"White, Not of Hispanic Origin",Y,94115,yes,True

In [25]:
random.notrandom.value_counts(False)

True     4470
False     141
Name: notrandom, dtype: int64

In [37]:
amountchoices = lotto.drop(['StudentNo', "Does Student Live In CTIP1 Zone? (y/n)",'School Enrolled In As Of 11/03/2017', 'Round 1 Assignment', "Student's Ethnicity", "Student's Residential Zip Code", 'got1stchoice'], axis=1)

In [41]:
lotto['choices'] = amountchoices.notnull().sum(axis=1)

In [42]:
amountchoices.reset_index()

,index,1,2,3,4,5,6,7,8,9,...,85,86,87,88,89,90,91,92,uniquechoices,morethan10
0,0,848,569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,no
1,1,420,420,537,729,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,no
2,2,478,589,722,664,539,796,420,413,569,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,yes
3,3,782,676,478,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,no
4,4,420,618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,no
5,5,838,746,478,876,488,848,729,569,796,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,no
6,6,485,876,513,513,478,862,862,782,760,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,no
7,7,859,449,790,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,no
8,8,420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
9,9,782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
10,10,485,676,862,750,746,539,435,782,644,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,no
11,11,676,796,485,478,478,420,420,497,589,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32,yes
12,12,842,722,575,478,488,876,420,796,539,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51,yes
13,13,862,876,509,862,876,488,490,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,no
14,14,676,485,750,644,782,876,746,876,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,no
15,15,746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
16,16,676,782,750,485,644,876,862,876,544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,no
17,17,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
18,18,796,420,478,722,876,718,589,479,413,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,yes
19,19,676,782,644,750,862,876,539,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,no
20,20,478,735,420,435,485,676,750,544,876,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,yes
21,21,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
22,22,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
23,23,569,479,782,750,644,413,876,435,485,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,yes
24,24,862,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,no
25,25,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
26,26,782,676,485,509,544,750,644,569,549,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,no
27,27,664,796,479,625,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,no
28,28,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
29,29,718,589,796,735,786,420,505,478,569,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4581,4581,420,420,876,722,796,862,488,478,842,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,no
4582,4582,485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
4583,4583,449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
4584,4584,814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
4585,4585,589,718,478,796,722,814,735,569,420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70,yes
4586,4586,507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
4587,4587,644,676,782,750,589,664,862,569,544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,no
4588,4588,537,420,456,680,618,760,723,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,no
4589,4589,796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
4590,4590,603,656,722,575,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,no
4591,4591,435,413,664,569,676,848,485,750,544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,yes
4592,4592,823,525,801,790,718,638,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,no
4593,4593,796,478,589,722,876,842,718,513,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,no
4594,4594,521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
4595,4595,760,449,796,420,435,488,478,722,479,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,no
4596,4596,750,876,876,478,478,485,676,644,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,no
4597,4597,796,420,420,876,478,589,718,485,722,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,no
4598,4598,816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
4599,4599,670,750,644,876,796,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,no
4600,4600,872,490,638,834,801,562,562,823,790,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,no
4601,4601,449,796,537,814,735,723,478,664,676,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,no
4602,4602,478,478,420,796,644,842,722,676,479,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,yes
4603,4603,618,714,537,729,723,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,no
4604,4604,478,478,876,876,796,589,420,420,575,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,yes
4605,4605,644,413,664,435,670,497,569,848,750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,no
4606,4606,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,no
4607,4607,618,796,760,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,no
4608,4608,820,488,691,691,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,no
4609,4609,834,490,638,562,525,650,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,no
4610,4610,718,722,814,823,413,420,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,no

In [29]:
lotto['morethan10'] = np.where(lotto['uniquechoices'] > 10, 'yes', 'no')

In [30]:
lotto.morethan10.value_counts('yes')

no     0.751247
yes    0.248753
Name: morethan10, dtype: float64

In [33]:
duplicates = lotto.drop(['StudentNo', "Does Student Live In CTIP1 Zone? (y/n)",'School Enrolled In As Of 11/03/2017', 'Round 1 Assignment', "Student's Ethnicity", "Student's Residential Zip Code", 'got1stchoice', 'morethan10'], axis=1)

In [43]:
duplicates['uniquechoices'] = duplicates.apply(lambda x: x.nunique(), axis=1)

In [35]:
duplicates.reset_index()

,index,1,2,3,4,5,6,7,8,9,...,84,85,86,87,88,89,90,91,92,uniquechoices
0,0,848,569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
1,1,420,420,537,729,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
2,2,478,589,722,664,539,796,420,413,569,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
3,3,782,676,478,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,4,420,618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
5,5,838,746,478,876,488,848,729,569,796,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
6,6,485,876,513,513,478,862,862,782,760,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
7,7,859,449,790,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
8,8,420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
9,9,782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
10,10,485,676,862,750,746,539,435,782,644,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
11,11,676,796,485,478,478,420,420,497,589,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30
12,12,842,722,575,478,488,876,420,796,539,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45
13,13,862,876,509,862,876,488,490,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
14,14,676,485,750,644,782,876,746,876,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
15,15,746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
16,16,676,782,750,485,644,876,862,876,544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
17,17,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
18,18,796,420,478,722,876,718,589,479,413,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
19,19,676,782,644,750,862,876,539,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
20,20,478,735,420,435,485,676,750,544,876,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
21,21,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
22,22,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
23,23,569,479,782,750,644,413,876,435,485,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
24,24,862,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
25,25,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
26,26,782,676,485,509,544,750,644,569,549,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
27,27,664,796,479,625,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
28,28,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
29,29,718,589,796,735,786,420,505,478,569,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4581,4581,420,420,876,722,796,862,488,478,842,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
4582,4582,485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4583,4583,449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4584,4584,814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4585,4585,589,718,478,796,722,814,735,569,420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68
4586,4586,507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4587,4587,644,676,782,750,589,664,862,569,544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
4588,4588,537,420,456,680,618,760,723,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
4589,4589,796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4590,4590,603,656,722,575,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4591,4591,435,413,664,569,676,848,485,750,544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12
4592,4592,823,525,801,790,718,638,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
4593,4593,796,478,589,722,876,842,718,513,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
4594,4594,521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4595,4595,760,449,796,420,435,488,478,722,479,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
4596,4596,750,876,876,478,478,485,676,644,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
4597,4597,796,420,420,876,478,589,718,485,722,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
4598,4598,816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4599,4599,670,750,644,876,796,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
4600,4600,872,490,638,834,801,562,562,823,790,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
4601,4601,449,796,537,814,735,723,478,664,676,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
4602,4602,478,478,420,796,644,842,722,676,479,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36
4603,4603,618,714,537,729,723,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
4604,4604,478,478,876,876,796,589,420,420,575,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
4605,4605,644,413,664,435,670,497,569,848,750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
4606,4606,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4607,4607,618,796,760,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4608,4608,820,488,691,691,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4609,4609,834,490,638,562,525,650,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
4610,4610,718,722,814,823,413,420,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7

In [44]:
lotto['amountduplicates'] = lotto['uniquechoices'] - duplicates['uniquechoices']

In [45]:
lotto.reset_index()

,index,StudentNo,1,2,3,4,5,6,7,8,...,Round 1 Assignment,School Enrolled In As Of 11/03/2017,Student's Ethnicity,Does Student Live In CTIP1 Zone? (y/n),Student's Residential Zip Code,got1stchoice,uniquechoices,morethan10,choices,amountduplicates
0,0,1,848,569,NaN,NaN,NaN,NaN,NaN,NaN,...,848,848,"White, Not of Hispanic Origin",N,94118,yes,4,no,4,1
1,1,2,420,420,537,729,NaN,NaN,NaN,NaN,...,729,729,Hispanic,N,94112,no,6,no,6,2
2,2,3,478,589,722,664,539,796,420,413,...,722,722,"White, Not of Hispanic Origin",N,94131,no,17,yes,17,1
3,3,4,782,676,478,NaN,NaN,NaN,NaN,NaN,...,782,782,Asian or Pacific Islander,N,94127,yes,5,no,5,1
4,4,5,420,618,NaN,NaN,NaN,NaN,NaN,NaN,...,420,420,Hispanic,Y,94110,yes,4,no,4,1
5,5,6,838,746,478,876,488,848,729,569,...,838,838,Asian or Pacific Islander,N,94134,yes,12,no,12,1
6,6,7,485,876,513,513,478,862,862,782,...,760,614,Declines To State,N,94134,no,11,no,11,3
7,7,8,859,449,790,NaN,NaN,NaN,NaN,NaN,...,859,859,Hispanic,N,94102,yes,5,no,5,1
8,8,9,420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,420,420,Declines To State,Y,94107,yes,3,no,3,1
9,9,10,782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,782,782,Declines To State,N,94112,yes,3,no,3,1
10,10,11,485,676,862,750,746,539,435,782,...,862,862,Asian or Pacific Islander,N,94116,no,12,no,12,1
11,11,12,676,796,485,478,478,420,420,497,...,676,676,Declines To State,Y,94107,yes,34,yes,34,4
12,12,13,842,722,575,478,488,876,420,796,...,842,842,"White, Not of Hispanic Origin",N,94127,yes,53,yes,53,8
13,13,14,862,876,509,862,876,488,490,NaN,...,490,490,Asian or Pacific Islander,N,94112,no,9,no,9,3
14,14,15,676,485,750,644,782,876,746,876,...,NaN,NaN,Asian or Pacific Islander,N,94132,no,10,no,10,2
15,15,16,746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,746,746,Declines To State,N,94112,yes,3,no,3,1
16,16,17,676,782,750,485,644,876,862,876,...,782,782,Asian or Pacific Islander,N,94132,no,12,no,12,2
17,17,18,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,435,435,Declines To State,N,94121,yes,3,no,3,1
18,18,19,796,420,478,722,876,718,589,479,...,420,NaN,Declines To State,N,94114,no,26,yes,26,1
19,19,20,676,782,644,750,862,876,539,NaN,...,676,676,Asian or Pacific Islander,N,94112,yes,9,no,9,1
20,20,21,478,735,420,435,485,676,750,544,...,478,478,"White, Not of Hispanic Origin",N,94122,yes,18,yes,18,1
21,21,22,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,867,867,Asian or Pacific Islander,N,94134,yes,3,no,3,1
22,22,23,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,488,488,Declines To State,N,94112,yes,3,no,3,1
23,23,24,569,479,782,750,644,413,876,435,...,656,860,Declines To State,N,94131,no,23,yes,23,1
24,24,25,862,867,NaN,NaN,NaN,NaN,NaN,NaN,...,867,525,Declines To State,N,94116,no,4,no,4,1
25,25,26,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,562,562,Hispanic,N,94117,yes,3,no,3,1
26,26,27,782,676,485,509,544,750,644,569,...,782,782,Asian or Pacific Islander,N,94103,yes,12,no,12,1
27,27,28,664,796,479,625,NaN,NaN,NaN,NaN,...,625,875,Hispanic,N,94129,no,6,no,6,1
28,28,29,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,562,562,Hispanic,N,94107,yes,3,no,3,1
29,29,30,718,589,796,735,786,420,505,478,...,718,718,"White, Not of Hispanic Origin",N,94114,yes,12,no,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4581,4581,4582,420,420,876,722,796,862,488,478,...,656,656,"White, Not of Hispanic Origin",N,94112,no,12,no,12,2
4582,4582,4583,485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,485,485,Asian or Pacific Islander,N,94112,yes,3,no,3,1
4583,4583,4584,449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,449,859,NaN,Y,94115,no,3,no,3,1
4584,4584,4585,814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,814,814,Hispanic,N,94124,yes,3,no,3,1
4585,4585,4586,589,718,478,796,722,814,735,569,...,589,938,"White, Not of Hispanic Origin",N,94117,no,72,yes,72,4
4586,4586,4587,507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,507,507,NaN,Y,94124,yes,3,no,3,1
4587,4587,4588,644,676,782,750,589,664,862,569,...,644,644,Asian or Pacific Islander,N,94122,yes,11,no,11,1
4588,4588,4589,537,420,456,680,618,760,723,NaN,...,456,456,Hispanic,N,94124,no,9,no,9,1
4589,4589,4590,796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,796,796,Hispanic,N,94134,yes,3,no,3,1
4590,4590,4591,603,656,722,575,NaN,NaN,NaN,NaN,...,603,614,Hispanic,N,94112,no,6,no,6,1
4591,4591,4592,435,413,664,569,676,848,485,750,...,859,544,Asian or Pacific Islander,N,94121,no,13,yes,13,1
4592,4592,4593,823,525,801,790,718,638,NaN,NaN,...,525,525,"Black, Not of Hispanic Origin",N,94115,no,8,no,8,1
4593,4593,4594,796,478,589,722,876,842,718,513,...,796,796,Asian or Pacific Islander,N,94134,yes,10,no,10,1
4594,4594,4595,521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,521,521,Hispanic,N,94134,yes,3,no,3,1
4595,4595,4596,760,449,796,420,435,488,478,722,...,760,760,Asian or Pacific Islander,N,94124,yes,12,no,12,1
4596,4596,4597,750,876,876,478,478,485,676,644,...,750,750,Asian or Pacific Islander,N,94122,yes,10,no,10,3
4597,4597,4598,796,420,420,876,478,589,718,485,...,420,420,NaN,N,94114,no,12,no,12,2
4598,4598,4599,816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,816,816,Hispanic,Y,94110,yes,3,no,3,1
4599,4599,4600,670,750,644,876,796,NaN,NaN,NaN,...,670,670,"White, Not of Hispanic Origin",N,94127,yes,7,no,7,1
4600,4600,4601,872,490,638,834,801,562,562,823,...,490,490,Asian or Pacific Islander,N,94108,no,12,no,12,2
4601,4601,4602,449,796,537,814,735,723,478,664,...,449,449,NaN,Y,94124,yes,12,no,12,1
4602,4602,4603,478,478,420,796,644,842,722,676,...,478,478,"White, Not of Hispanic Origin",Y,94109,yes,39,yes,39,3
4603,4603,4604,618,714,537,729,723,NaN,NaN,NaN,...,618,618,Hispanic,Y,94110,yes,7,no,7,1
4604,4604,4605,478,478,876,876,796,589,420,420,...,816,201,NaN,N,94131,no,24,yes,24,4
4605,4605,4606,644,413,664,435,670,497,569,848,...,670,670,"White, Not of Hispanic Origin",N,94118,no,12,no,12,1
4606,4606,4607,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,867,867,Asian or Pacific Islander,N,94134,yes,3,no,3,1
4607,4607,4608,618,796,760,NaN,NaN,NaN,NaN,NaN,...,618,618,NaN,N,94110,yes,5,no,5,1
4608,4608,4609,820,488,691,691,NaN,NaN,NaN,NaN,...,820,820,Hispanic,N,94112,yes,6,no,6,2
4609,4609,4610,834,490,638,562,525,650,NaN,NaN,...,834,834,NaN,Y,94109,yes,8,no,8,1
4610,4610,4611,718,722,814,823,413,420,NaN,NaN,...,718,718,"White, Not of Hispanic Origin",Y,94115,yes,8,no,8,1

In [ ]:
lotto.groupby(['got1stchoice', 'morethan10']).size()

In [ ]:
lotto.reset_index()

In [46]:
pd.Series(['M', '0', 'M', '0']).duplicated()

0    False
1    False
2     True
3     True
dtype: bool