# KQED's analysis of the 2017-2018 schol year kindergarten lottery

Import pandas and numpy. Import data.

In [35]:
import pandas as pd

In [36]:
import numpy as np

In [37]:
lotto = pd.read_csv('/Users/pickoffwhite/Code/kindergarten-lotto/20171103_ KQED_KinderAssignmentData_201718 - K Placement 2017-2018.csv', dtype = object)

How many students enrolled in their first choice school?

In [38]:
lotto['got1stchoice'] = np.where(lotto['1'] == lotto['School Enrolled In As Of 11/03/2017'], 'yes', 'no')

In [39]:
lotto.got1stchoice.value_counts()

yes    2810
no     1801
Name: got1stchoice, dtype: int64

In [40]:
lotto.got1stchoice.value_counts('yes')

yes    0.609412
no     0.390588
Name: got1stchoice, dtype: float64

However, there are students that entered the lottery late. The school that those students enroll in becomes their first choice in the data. We are going to exclude them from the dataset. We can tell who they are because they did not received a round one assignment, so their data is null, according to the San Francisco School District.

In [41]:
lotto.dropna(subset=['Round 1 Assignment'])

,StudentNo,1,2,3,4,5,6,7,8,9,...,89,90,91,92,Round 1 Assignment,School Enrolled In As Of 11/03/2017,Student's Ethnicity,Does Student Live In CTIP1 Zone? (y/n),Student's Residential Zip Code,got1stchoice
0,1,848,569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,848,848,"White, Not of Hispanic Origin",N,94118,yes
1,2,420,420,537,729,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,729,729,Hispanic,N,94112,no
2,3,478,589,722,664,539,796,420,413,569,...,NaN,NaN,NaN,NaN,722,722,"White, Not of Hispanic Origin",N,94131,no
3,4,782,676,478,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,782,782,Asian or Pacific Islander,N,94127,yes
4,5,420,618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,420,420,Hispanic,Y,94110,yes
5,6,838,746,478,876,488,848,729,569,796,...,NaN,NaN,NaN,NaN,838,838,Asian or Pacific Islander,N,94134,yes
6,7,485,876,513,513,478,862,862,782,760,...,NaN,NaN,NaN,NaN,760,614,Declines To State,N,94134,no
7,8,859,449,790,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,859,859,Hispanic,N,94102,yes
8,9,420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,420,420,Declines To State,Y,94107,yes
9,10,782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,782,782,Declines To State,N,94112,yes
10,11,485,676,862,750,746,539,435,782,644,...,NaN,NaN,NaN,NaN,862,862,Asian or Pacific Islander,N,94116,no
11,12,676,796,485,478,478,420,420,497,589,...,NaN,NaN,NaN,NaN,676,676,Declines To State,Y,94107,yes
12,13,842,722,575,478,488,876,420,796,539,...,NaN,NaN,NaN,NaN,842,842,"White, Not of Hispanic Origin",N,94127,yes
13,14,862,876,509,862,876,488,490,NaN,NaN,...,NaN,NaN,NaN,NaN,490,490,Asian or Pacific Islander,N,94112,no
15,16,746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,746,746,Declines To State,N,94112,yes
16,17,676,782,750,485,644,876,862,876,544,...,NaN,NaN,NaN,NaN,782,782,Asian or Pacific Islander,N,94132,no
17,18,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,435,435,Declines To State,N,94121,yes
18,19,796,420,478,722,876,718,589,479,413,...,NaN,NaN,NaN,NaN,420,NaN,Declines To State,N,94114,no
19,20,676,782,644,750,862,876,539,NaN,NaN,...,NaN,NaN,NaN,NaN,676,676,Asian or Pacific Islander,N,94112,yes
20,21,478,735,420,435,485,676,750,544,876,...,NaN,NaN,NaN,NaN,478,478,"White, Not of Hispanic Origin",N,94122,yes
21,22,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,867,867,Asian or Pacific Islander,N,94134,yes
22,23,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,488,488,Declines To State,N,94112,yes
23,24,569,479,782,750,644,413,876,435,485,...,NaN,NaN,NaN,NaN,656,860,Declines To State,N,94131,no
24,25,862,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,867,525,Declines To State,N,94116,no
25,26,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,562,562,Hispanic,N,94117,yes
26,27,782,676,485,509,544,750,644,569,549,...,NaN,NaN,NaN,NaN,782,782,Asian or Pacific Islander,N,94103,yes
27,28,664,796,479,625,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,625,875,Hispanic,N,94129,no
28,29,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,562,562,Hispanic,N,94107,yes
29,30,718,589,796,735,786,420,505,478,569,...,NaN,NaN,NaN,NaN,718,718,"White, Not of Hispanic Origin",N,94114,yes
30,31,509,485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,509,509,Declines To State,N,94132,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4581,4582,420,420,876,722,796,862,488,478,842,...,NaN,NaN,NaN,NaN,656,656,"White, Not of Hispanic Origin",N,94112,no
4582,4583,485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,485,485,Asian or Pacific Islander,N,94112,yes
4583,4584,449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,449,859,NaN,Y,94115,no
4584,4585,814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,814,814,Hispanic,N,94124,yes
4585,4586,589,718,478,796,722,814,735,569,420,...,NaN,NaN,NaN,NaN,589,938,"White, Not of Hispanic Origin",N,94117,no
4586,4587,507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,507,507,NaN,Y,94124,yes
4587,4588,644,676,782,750,589,664,862,569,544,...,NaN,NaN,NaN,NaN,644,644,Asian or Pacific Islander,N,94122,yes
4588,4589,537,420,456,680,618,760,723,NaN,NaN,...,NaN,NaN,NaN,NaN,456,456,Hispanic,N,94124,no
4589,4590,796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,796,796,Hispanic,N,94134,yes
4590,4591,603,656,722,575,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,603,614,Hispanic,N,94112,no
4591,4592,435,413,664,569,676,848,485,750,544,...,NaN,NaN,NaN,NaN,859,544,Asian or Pacific Islander,N,94121,no
4592,4593,823,525,801,790,718,638,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,525,525,"Black, Not of Hispanic Origin",N,94115,no
4593,4594,796,478,589,722,876,842,718,513,NaN,...,NaN,NaN,NaN,NaN,796,796,Asian or Pacific Islander,N,94134,yes
4594,4595,521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,521,521,Hispanic,N,94134,yes
4595,4596,760,449,796,420,435,488,478,722,479,...,NaN,NaN,NaN,NaN,760,760,Asian or Pacific Islander,N,94124,yes
4596,4597,750,876,876,478,478,485,676,644,NaN,...,NaN,NaN,NaN,NaN,750,750,Asian or Pacific Islander,N,94122,yes
4597,4598,796,420,420,876,478,589,718,485,722,...,NaN,NaN,NaN,NaN,420,420,NaN,N,94114,no
4598,4599,816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,816,816,Hispanic,Y,94110,yes
4599,4600,670,750,644,876,796,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,670,670,"White, Not of Hispanic Origin",N,94127,yes
4600,4601,872,490,638,834,801,562,562,823,790,...,NaN,NaN,NaN,NaN,490,490,Asian or Pacific Islander,N,94108,no
4601,4602,449,796,537,814,735,723,478,664,676,...,NaN,NaN,NaN,NaN,449,449,NaN,Y,94124,yes
4602,4603,478,478,420,796,644,842,722,676,479,...,NaN,NaN,NaN,NaN,478,478,"White, Not of Hispanic Origin",Y,94109,yes
4603,4604,618,714,537,729,723,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,618,618,Hispanic,Y,94110,yes
4604,4605,478,478,876,876,796,589,420,420,575,...,NaN,NaN,NaN,NaN,816,201,NaN,N,94131,no
4605,4606,644,413,664,435,670,497,569,848,750,...,NaN,NaN,NaN,NaN,670,670,"White, Not of Hispanic Origin",N,94118,no
4606,4607,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,867,867,Asian or Pacific Islander,N,94134,yes
4607,4608,618,796,760,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,618,618,NaN,N,94110,yes
4608,4609,820,488,691,691,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,820,820,Hispanic,N,94112,yes
4609,4610,834,490,638,562,525,650,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,834,834,NaN,Y,94109,yes
4610,4611,718,722,814,823,413,420,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,718,718,"White, Not of Hispanic Origin",Y,94115,yes

So let's rerun the code.

In [42]:
lotto.got1stchoice.value_counts('yes')

yes    0.609412
no     0.390588
Name: got1stchoice, dtype: float64

Code to determine how many students enrolled in one of the schools in their first five choices. We're filtering down the dataframe to the first five schools, and then seeing how many match.

In [43]:
lotto5 = lotto[['School Enrolled In As Of 11/03/2017','1','2','3','4','5']]

In [44]:
lotto['gottop5'] = lotto5.drop("School Enrolled In As Of 11/03/2017", 1).isin(lotto5["School Enrolled In As Of 11/03/2017"]).any(1)

In [46]:
lotto.gottop5.value_counts(True)

True     0.766645
False    0.233355
Name: gottop5, dtype: float64

Code to determine how many students enrolled in one of the schools in their first ten choices. We're filtering down the dataframe to the first ten schools, and then seeing how many match.

In [47]:
lotto10 = lotto[['School Enrolled In As Of 11/03/2017','1','2','3','4','5', '6', '7', '8', '9', '10']]

In [48]:
lotto['gottop10'] = lotto10.drop("School Enrolled In As Of 11/03/2017", 1).isin(lotto10["School Enrolled In As Of 11/03/2017"]).any(1)

In [49]:
lotto.reset_index()

,index,StudentNo,1,2,3,4,5,6,7,8,...,91,92,Round 1 Assignment,School Enrolled In As Of 11/03/2017,Student's Ethnicity,Does Student Live In CTIP1 Zone? (y/n),Student's Residential Zip Code,got1stchoice,gottop5,gottop10
0,0,1,848,569,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,848,848,"White, Not of Hispanic Origin",N,94118,yes,True,True
1,1,2,420,420,537,729,NaN,NaN,NaN,NaN,...,NaN,NaN,729,729,Hispanic,N,94112,no,True,True
2,2,3,478,589,722,664,539,796,420,413,...,NaN,NaN,722,722,"White, Not of Hispanic Origin",N,94131,no,True,True
3,3,4,782,676,478,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,782,782,Asian or Pacific Islander,N,94127,yes,True,True
4,4,5,420,618,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,420,420,Hispanic,Y,94110,yes,True,True
5,5,6,838,746,478,876,488,848,729,569,...,NaN,NaN,838,838,Asian or Pacific Islander,N,94134,yes,True,True
6,6,7,485,876,513,513,478,862,862,782,...,NaN,NaN,760,614,Declines To State,N,94134,no,False,False
7,7,8,859,449,790,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,859,859,Hispanic,N,94102,yes,True,True
8,8,9,420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,420,420,Declines To State,Y,94107,yes,True,True
9,9,10,782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,782,782,Declines To State,N,94112,yes,True,True
10,10,11,485,676,862,750,746,539,435,782,...,NaN,NaN,862,862,Asian or Pacific Islander,N,94116,no,True,True
11,11,12,676,796,485,478,478,420,420,497,...,NaN,NaN,676,676,Declines To State,Y,94107,yes,True,True
12,12,13,842,722,575,478,488,876,420,796,...,NaN,NaN,842,842,"White, Not of Hispanic Origin",N,94127,yes,True,True
13,13,14,862,876,509,862,876,488,490,NaN,...,NaN,NaN,490,490,Asian or Pacific Islander,N,94112,no,False,True
14,14,15,676,485,750,644,782,876,746,876,...,NaN,NaN,NaN,NaN,Asian or Pacific Islander,N,94132,no,False,False
15,15,16,746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,746,746,Declines To State,N,94112,yes,True,True
16,16,17,676,782,750,485,644,876,862,876,...,NaN,NaN,782,782,Asian or Pacific Islander,N,94132,no,True,True
17,17,18,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,435,435,Declines To State,N,94121,yes,True,True
18,18,19,796,420,478,722,876,718,589,479,...,NaN,NaN,420,NaN,Declines To State,N,94114,no,False,False
19,19,20,676,782,644,750,862,876,539,NaN,...,NaN,NaN,676,676,Asian or Pacific Islander,N,94112,yes,True,True
20,20,21,478,735,420,435,485,676,750,544,...,NaN,NaN,478,478,"White, Not of Hispanic Origin",N,94122,yes,True,True
21,21,22,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,867,867,Asian or Pacific Islander,N,94134,yes,True,True
22,22,23,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,488,488,Declines To State,N,94112,yes,True,True
23,23,24,569,479,782,750,644,413,876,435,...,NaN,NaN,656,860,Declines To State,N,94131,no,False,False
24,24,25,862,867,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,867,525,Declines To State,N,94116,no,False,False
25,25,26,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,562,562,Hispanic,N,94117,yes,True,True
26,26,27,782,676,485,509,544,750,644,569,...,NaN,NaN,782,782,Asian or Pacific Islander,N,94103,yes,True,True
27,27,28,664,796,479,625,NaN,NaN,NaN,NaN,...,NaN,NaN,625,875,Hispanic,N,94129,no,False,False
28,28,29,562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,562,562,Hispanic,N,94107,yes,True,True
29,29,30,718,589,796,735,786,420,505,478,...,NaN,NaN,718,718,"White, Not of Hispanic Origin",N,94114,yes,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4581,4581,4582,420,420,876,722,796,862,488,478,...,NaN,NaN,656,656,"White, Not of Hispanic Origin",N,94112,no,False,True
4582,4582,4583,485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,485,485,Asian or Pacific Islander,N,94112,yes,True,True
4583,4583,4584,449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,449,859,NaN,Y,94115,no,False,False
4584,4584,4585,814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,814,814,Hispanic,N,94124,yes,True,True
4585,4585,4586,589,718,478,796,722,814,735,569,...,NaN,NaN,589,938,"White, Not of Hispanic Origin",N,94117,no,False,False
4586,4586,4587,507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,507,507,NaN,Y,94124,yes,True,True
4587,4587,4588,644,676,782,750,589,664,862,569,...,NaN,NaN,644,644,Asian or Pacific Islander,N,94122,yes,True,True
4588,4588,4589,537,420,456,680,618,760,723,NaN,...,NaN,NaN,456,456,Hispanic,N,94124,no,True,True
4589,4589,4590,796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,796,796,Hispanic,N,94134,yes,True,True
4590,4590,4591,603,656,722,575,NaN,NaN,NaN,NaN,...,NaN,NaN,603,614,Hispanic,N,94112,no,False,False
4591,4591,4592,435,413,664,569,676,848,485,750,...,NaN,NaN,859,544,Asian or Pacific Islander,N,94121,no,False,True
4592,4592,4593,823,525,801,790,718,638,NaN,NaN,...,NaN,NaN,525,525,"Black, Not of Hispanic Origin",N,94115,no,True,True
4593,4593,4594,796,478,589,722,876,842,718,513,...,NaN,NaN,796,796,Asian or Pacific Islander,N,94134,yes,True,True
4594,4594,4595,521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,521,521,Hispanic,N,94134,yes,True,True
4595,4595,4596,760,449,796,420,435,488,478,722,...,NaN,NaN,760,760,Asian or Pacific Islander,N,94124,yes,True,True
4596,4596,4597,750,876,876,478,478,485,676,644,...,NaN,NaN,750,750,Asian or Pacific Islander,N,94122,yes,True,True
4597,4597,4598,796,420,420,876,478,589,718,485,...,NaN,NaN,420,420,NaN,N,94114,no,True,True
4598,4598,4599,816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,816,816,Hispanic,Y,94110,yes,True,True
4599,4599,4600,670,750,644,876,796,NaN,NaN,NaN,...,NaN,NaN,670,670,"White, Not of Hispanic Origin",N,94127,yes,True,True
4600,4600,4601,872,490,638,834,801,562,562,823,...,NaN,NaN,490,490,Asian or Pacific Islander,N,94108,no,True,True
4601,4601,4602,449,796,537,814,735,723,478,664,...,NaN,NaN,449,449,NaN,Y,94124,yes,True,True
4602,4602,4603,478,478,420,796,644,842,722,676,...,NaN,NaN,478,478,"White, Not of Hispanic Origin",Y,94109,yes,True,True
4603,4603,4604,618,714,537,729,723,NaN,NaN,NaN,...,NaN,NaN,618,618,Hispanic,Y,94110,yes,True,True
4604,4604,4605,478,478,876,876,796,589,420,420,...,NaN,NaN,816,201,NaN,N,94131,no,False,False
4605,4605,4606,644,413,664,435,670,497,569,848,...,NaN,NaN,670,670,"White, Not of Hispanic Origin",N,94118,no,True,True
4606,4606,4607,867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,867,867,Asian or Pacific Islander,N,94134,yes,True,True
4607,4607,4608,618,796,760,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,618,618,NaN,N,94110,yes,True,True
4608,4608,4609,820,488,691,691,NaN,NaN,NaN,NaN,...,NaN,NaN,820,820,Hispanic,N,94112,yes,True,True
4609,4609,4610,834,490,638,562,525,650,NaN,NaN,...,NaN,NaN,834,834,NaN,Y,94109,yes,True,True
4610,4610,4611,718,722,814,823,413,420,NaN,NaN,...,NaN,NaN,718,718,"White, Not of Hispanic Origin",Y,94115,yes,True,True

So how many students enrolled in one of their top five choices?

In [50]:
lotto.gottop5.value_counts(True)

True     0.766645
False    0.233355
Name: gottop5, dtype: float64

So how many students enrolled in one of their top ten choices?

In [51]:
lotto.gottop10.value_counts(True)

True     0.796573
False    0.203427
Name: gottop10, dtype: float64

How many students are assigned a random school in round one?

In [52]:
random = lotto.drop(['StudentNo', 'School Enrolled In As Of 11/03/2017'], axis=1)

In [53]:
random['notrandom'] = random.drop('Round 1 Assignment', 1).isin(random['Round 1 Assignment']).any(1)
print(random)

        1    2    3    4    5    6    7    8    9   10    ...      91   92  \
0     848  569  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
1     420  420  537  729  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
2     478  589  722  664  539  796  420  413  569  750    ...     NaN  NaN
3     782  676  478  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4     420  618  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
5     838  746  478  876  488  848  729  569  796  676    ...     NaN  NaN
6     485  876  513  513  478  862  862  782  760  NaN    ...     NaN  NaN
7     859  449  790  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
8     420  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
9     782  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
10    485  676  862  750  746  539  435  782  644  876    ...     NaN  NaN
11    676  796  485  478  478  420  420  497  589  876    ...     NaN  NaN
12    842  722  575  478  488  876  420  796  539  862    ...     NaN  NaN
13    862  876  509  862  876  488  490  NaN  NaN  NaN    ...     NaN  NaN
14    676  485  750  644  782  876  746  876  NaN  NaN    ...     NaN  NaN
15    746  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
16    676  782  750  485  644  876  862  876  544  435    ...     NaN  NaN
17    435  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
18    796  420  478  722  876  718  589  479  413  485    ...     NaN  NaN
19    676  782  644  750  862  876  539  NaN  NaN  NaN    ...     NaN  NaN
20    478  735  420  435  485  676  750  544  876  505    ...     NaN  NaN
21    867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
22    488  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
23    569  479  782  750  644  413  876  435  485  676    ...     NaN  NaN
24    862  867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
25    562  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
26    782  676  485  509  544  750  644  569  549  735    ...     NaN  NaN
27    664  796  479  625  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
28    562  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
29    718  589  796  735  786  420  505  478  569  823    ...     NaN  NaN
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...     ...  ...
4581  420  420  876  722  796  862  488  478  842  656    ...     NaN  NaN
4582  485  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4583  449  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4584  814  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4585  589  718  478  796  722  814  735  569  420  435    ...     NaN  NaN
4586  507  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4587  644  676  782  750  589  664  862  569  544  NaN    ...     NaN  NaN
4588  537  420  456  680  618  760  723  NaN  NaN  NaN    ...     NaN  NaN
4589  796  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4590  603  656  722  575  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4591  435  413  664  569  676  848  485  750  544  746    ...     NaN  NaN
4592  823  525  801  790  718  638  NaN  NaN  NaN  NaN    ...     NaN  NaN
4593  796  478  589  722  876  842  718  513  NaN  NaN    ...     NaN  NaN
4594  521  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4595  760  449  796  420  435  488  478  722  479  539    ...     NaN  NaN
4596  750  876  876  478  478  485  676  644  NaN  NaN    ...     NaN  NaN
4597  796  420  420  876  478  589  718  485  722  537    ...     NaN  NaN
4598  816  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4599  670  750  644  876  796  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4600  872  490  638  834  801  562  562  823  790  859    ...     NaN  NaN
4601  449  796  537  814  735  723  478  664  676  420    ...     NaN  NaN
4602  478  478  420  796  644  842  722  676  479  735    ...     NaN  NaN
4603  618  714  537  729  723  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4604  478  478  876  876  796  589  420  420  575  718    ...     NaN  NaN
4605  644  413  664  435  670  497  569  848  750  842    ...     NaN  NaN
4606  867  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4607  618  796  760  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4608  820  488  691  691  NaN  NaN  NaN  NaN  NaN  NaN    ...     NaN  NaN
4609  834  490  638  562  525  650  NaN  NaN  NaN  NaN    ...     NaN  NaN
4610  718  722  814  823  413  420  NaN  NaN  NaN  NaN    ...     NaN  NaN

     Round 1 Assignment            Student's Ethnicity  \
0                   848  White, Not of Hispanic Origin
1                   729                       Hispanic
2                   722  White, Not of Hispanic Origin
3                   782      Asian or Pacific Islander
4                   420                       Hispanic
5                   838      Asian or Pacific Islander
6                   760              Declines To State
7                   859                       Hispanic
8                   420              Declines To State
9                   782              Declines To State
10                  862      Asian or Pacific Islander
11                  676              Declines To State
12                  842  White, Not of Hispanic Origin
13                  490      Asian or Pacific Islander
14                  NaN      Asian or Pacific Islander
15                  746              Declines To State
16                  782      Asian or Pacific Islander
17                  435              Declines To State
18                  420              Declines To State
19                  676      Asian or Pacific Islander
20                  478  White, Not of Hispanic Origin
21                  867      Asian or Pacific Islander
22                  488              Declines To State
23                  656              Declines To State
24                  867              Declines To State
25                  562                       Hispanic
26                  782      Asian or Pacific Islander
27                  625                       Hispanic
28                  562                       Hispanic
29                  718  White, Not of Hispanic Origin
...                 ...                            ...
4581                656  White, Not of Hispanic Origin
4582                485      Asian or Pacific Islander
4583                449                            NaN
4584                814                       Hispanic
4585                589  White, Not of Hispanic Origin
4586                507                            NaN
4587                644      Asian or Pacific Islander
4588                456                       Hispanic
4589                796                       Hispanic
4590                603                       Hispanic
4591                859      Asian or Pacific Islander
4592                525  Black, Not of Hispanic Origin
4593                796      Asian or Pacific Islander
4594                521                       Hispanic
4595                760      Asian or Pacific Islander
4596                750      Asian or Pacific Islander
4597                420                            NaN
4598                816                       Hispanic
4599                670  White, Not of Hispanic Origin
4600                490      Asian or Pacific Islander
4601                449                            NaN
4602                478  White, Not of Hispanic Origin
4603                618                       Hispanic
4604                816                            NaN
4605                670  White, Not of Hispanic Origin
4606                867      Asian or Pacific Islander
4607                618                            NaN
4608                820                       Hispanic
4609                834                            NaN
4610                718  White, Not of Hispanic Origin

     Does Student Live In CTIP1 Zone? (y/n) Student's Residential Zip Code  \
0                                         N                          94118
1                                         N                          94112
2                                         N                          94131
3                                         N                          94127
4                                         Y                          94110
5                                         N                          94134
6                                         N                          94134
7                                         N                          94102
8                                         Y                          94107
9                                         N                          94112
10                                        N                          94116
11                                        Y                          94107
12                                        N                          94127
13                                        N                          94112
14                                        N                          94132
15                                        N                          94112
16                                        N                          94132
17                                        N                          94121
18                                        N                          94114
19                                        N                          94112
20                                        N                          94122
21                                        N                          94134
22                                        N                          94112
23                                        N                          94131
24                                        N                          94116
25                                        N                          94117
26                                        N                          94103
27                                        N                          94129
28                                        N                          94107
29                                        N                          94114
...                                     ...                            ...
4581                                      N                          94112
4582                                      N                          94112
4583                                      Y                          94115
4584                                      N                          94124
4585                                      N                          94117
4586                                      Y                          94124
4587                                      N                          94122
4588                                      N                          94124
4589                                      N                          94134
4590                                      N                          94112
4591                                      N                          94121
4592                                      N                          94115
4593                                      N                          94134
4594                                      N                          94134
4595                                      N                          94124
4596                                      N                          94122
4597                                      N                          94114
4598                                      Y                          94110
4599                                      N                          94127
4600                                      N                          94108
4601                                      Y                          94124
4602                                      Y                          94109
4603                                      Y                          94110
4604                                      N                          94131
4605                                      N                          94118
4606                                      N                          94134
4607                                      N                          94110
4608                                      N                          94112
4609                                      Y                          94109
4610                                      Y                          94115

     got1stchoice gottop5 gottop10 notrandom
0             yes    True     True      True
1              no    True     True      True
2              no    True     True      True
3             yes    True     True      True
4             yes    True     True      True
5             yes    True     True      True
6              no   False    False      True
7             yes    True     True      True
8             yes    True     True      True
9             yes    True     True      True
10             no    True     True      True
11            yes    True     True      True
12            yes    True     True      True
13             no   False     True      True
14             no   False    False     False
15            yes    True     True      True
16             no    True     True      True
17            yes    True     True      True
18             no   False    False      True
19            yes    True     True      True
20            yes    True     True      True
21            yes    True     True      True
22            yes    True     True      True
23             no   False    False      True
24             no   False    False      True
25            yes    True     True      True
26            yes    True     True      True
27             no   False    False      True
28            yes    True     True      True
29            yes    True     True      True
...           ...     ...      ...       ...
4581           no   False     True      True
4582          yes    True     True      True
4583           no   False    False      True
4584          yes    True     True      True
4585           no   False    False      True
4586          yes    True     True      True
4587          yes    True     True      True
4588           no    True     True      True
4589          yes    True     True      True
4590           no   False    False      True
4591           no   False     True      True
4592           no    True     True      True
4593          yes    True     True      True
4594          yes    True     True      True
4595          yes    True     True      True
4596          yes    True     True      True
4597           no    True     True      True
4598          yes    True     True      True
4599          yes    True     True      True
4600           no    True     True      True
4601          yes    True     True      True
4602          yes    True     True      True
4603          yes    True     True      True
4604           no   False    False      True
4605           no    True     True      True
4606          yes    True     True      True
4607          yes    True     True      True
4608          yes    True     True      True
4609          yes    True     True      True
4610          yes    True     True      True

[4611 rows x 100 columns]

In [ ]:
random.notrandom.value_counts(False)

Analysing how many people put down more than 10 school choices.

In [54]:
amountchoices = lotto.drop(['StudentNo', "Does Student Live In CTIP1 Zone? (y/n)",'School Enrolled In As Of 11/03/2017', 'Round 1 Assignment', "Student's Ethnicity", "Student's Residential Zip Code", 'got1stchoice', 'gottop5', 'gottop10'], axis=1)

In [55]:
lotto['choices'] = amountchoices.notnull().sum(axis=1)

In [56]:
lotto['morethan10'] = np.where(lotto['choices'] > 10, 'yes', 'no')

In [ ]:
lotto.morethan10.value_counts('yes')

Examining how many people put down duplicate choices.

In [57]:
duplicates = lotto.drop(['StudentNo', "Does Student Live In CTIP1 Zone? (y/n)",'School Enrolled In As Of 11/03/2017', 'Round 1 Assignment', "Student's Ethnicity", "Student's Residential Zip Code", 'got1stchoice', 'gottop5', 'gottop10', 'choices', 'morethan10' ], axis=1)

In [58]:
duplicates['uniquechoices'] = duplicates.apply(lambda x: x.nunique(), axis=1)

In [59]:
lotto['amountduplicates'] = lotto['choices'] - duplicates['uniquechoices']

In [60]:
lotto['duplicates'] = np.where(lotto['amountduplicates'] > 0, 'yes', 'no')

In [61]:
lotto.duplicates.value_counts('no')

no     0.642811
yes    0.357189
Name: duplicates, dtype: float64

Does putting down more than ten schools impact the chance of enrolling in your first choice?

In [62]:
lotto.groupby(['got1stchoice', 'morethan10']).size()

got1stchoice  morethan10
no            no            1105
              yes            696
yes           no            2359
              yes            451
dtype: int64

Does putting down duplicates impact the chance of enrolling in your first choice?

In [63]:
lotto.groupby(['got1stchoice', 'duplicates']).size()

got1stchoice  duplicates
no            no            1035
              yes            766
yes           no            1929
              yes            881
dtype: int64